- name: Get subnet info
  ec2_vpc_subnet_info:
    filters:
      "tag:Ansible": "{{ tag }}"
  register: subnet_info

- community.aws.ec2_asg:
    name: "{{ asg.name }}"
    launch_template:
      launch_template_name: "{{ launch_template.name }}"
    min_size: "{{ asg.min_size }}"
    max_size: "{{ asg.max_size }}"
    tags:
      - Ansible: "{{ tag }}"
    vpc_zone_identifier: ["{{ subnet_info.subnets | selectattr('tags.Name', 'search', asg.deployed_subnet_a) | map(attribute='subnet_id') | first }}", "{{ subnet_info.subnets | selectattr('tags.Name', 'search', asg.deployed_subnet_c) | map(attribute='subnet_id') | first }}"]
