# Create PRIVATE_SUBNET
- name: Create private subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_info.vpc.id }}"
    cidr: "{{ item.pri_subnet_cidr }}"
    az: "{{ item.subnet_az }}"
    region: "{{ region }}"
    tags: { "Name":"{{ item.pri_subnet_name }}", "Ansible": "{{ tag }}" }
  register: prisub_info
  with_items:
    - "{{ pri_subnet }}"

